export const navigation = [
	{
		title: 'Skyrim',
		image: 'skyrim.jpg',
		url: '/skyrim',
		enabled: true,
	},
	// {
	// 	title: 'Starfield',
	// 	image: 'starfield.jpg',
	// 	url: '/starfield',
	// 	enabled: true,
	// },
	{
		title: 'Terraria',
		image: 'terraria.jpg',
		url: '/terraria',
		enabled: true,
	},
	{
		title: 'GTA V',
		image: 'gtav.jpg',
		url: '/gtav',
		enabled: false,
	},
	{
		title: 'Elden Ring',
		image: 'eldenring.jpg',
		url: '/eldenring',
		enabled: false,
	},
	{
		title: 'Zelda: ToTK',
		image: 'zeldatearsofkingom.jpg',
		url: '/zeldatearsofkingom',
		enabled: false,
	},
	{
		title: 'The Witcher 3',
		image: 'witcher3.jpg',
		url: '/witcher3',
		enabled: false,
	},
	{
		title: 'League of Legends',
		image: 'leagueoflegends.jpg',
		url: '/leagueoflegends',
		enabled: false,
	},
	{
		title: 'Genshin Impact',
		image: 'genshinimpact.jpg',
		url: '/genshinimpact',
		enabled: false,
	},
	{
		title: 'Hogwarts Legacy',
		image: 'hogwartslegacy.jpg',
		url: '/hogwartslegacy',
		enabled: false,
	},
	{
		title: 'Cyberpunk 2077',
		image: 'cyberpunk.jpg',
		url: '/cyberpunk',
		enabled: false,
	},
	{
		title: 'Stardew Valley',
		image: 'stardewvalley.jpg',
		url: '/stardewvalley',
		enabled: false,
	},
	{
		title: 'Dark Souls 3',
		image: 'darksouls3.jpg',
		url: '/darksouls3',
		enabled: false,
	},
	{
		title: 'Monster Hunter Rise',
		image: 'monsterhunterrise.jpg',
		url: '/monsterhunterrise',
		enabled: false,
	},
	{
		title: 'Diablo IV',
		image: 'diabloIV.jpg',
		url: '/diabloIV',
		enabled: false,
	},
	{
		title: 'Minecraft',
		image: 'minecraft.jpg',
		url: '/minecraft',
		enabled: false,
	},
	{
		title: 'The Last of Us Part I',
		image: 'lastofuspartI.jpg',
		url: '/lastofuspartI',
		enabled: false,
	},
	{
		title: 'Lost Ark',
		image: 'lostark.jpg',
		url: '/lostark',
		enabled: false,
	},
	{
		title: "Baldur's Gate 3",
		image: 'baldursgate3.jpg',
		url: '/baldursgate3',
		enabled: false,
	},
	{
		title: 'Mass Effect 3',
		image: 'masseffect3.jpg',
		url: '/masseffect3',
		enabled: false,
	},
	{
		title: 'Fallout 4',
		image: 'fallout4.jpg',
		url: '/fallout4',
		enabled: false,
	},
	{
		title: 'Fallout: New Vegas',
		image: 'falloutnewvegas.jpg',
		url: '/falloutnewvegas',
		enabled: false,
	},
	{
		title: 'Oblivion',
		image: 'oblivion.jpg',
		url: '/oblivion',
		enabled: false,
	},
	{
		title: 'Fallout 3',
		image: 'fallout3.jpg',
		url: '/fallout3',
		enabled: false,
	},
	{
		title: 'Escape from Tarkov',
		image: 'escapefromtarkov.jpg',
		url: '/escapefromtarkov',
		enabled: false,
	},
]
